config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :users, only: [:update]

  resources :topics do
    resources :posts, except: [:index] do
      resources :comments, only: [:create]
    end
  end

  get 'about' => 'welcome#about'

  root to: 'welcome#index'

end

app/models/advertisement.rb
class Advertisement < ActiveRecord::Base
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user


  validates :body, length: { minimum: 5}, presence: true
  validates :body, presence: true
  validates :user_id, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  belongs_to :user
  belongs_to :topic
  mount_uploader :image, ImageUploader

  default_scope { order('created_at DESC') }

  validates :title, length: { minimum: 5}, presence: true
  validates :body, length: { minimum: 20}, presence: true
  validates :topic, presence: true
  validates :user, presence: true
end

app/models/question.rb
class Question < ActiveRecord::Base
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :posts
  self.per_page = 50
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :posts
  has_many :comments
  mount_uploader :avatar, AvatarUploader
  def admin?
    role == 'admin'
  end

  def moderator?
    role == 'moderator'
  end


end

app/controllers/advertisements_controller.rb
class AdvertisementsController < ApplicationController

  def index
    @advertisements = Advertisement.all
  end

  def show
    @advertisement = Advertisement.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from Pundit::NotAuthorizedError do |exception|
    redirect_to root_url, alert: exception.message
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    #create a new comment associated with a post
    #and associated with the current user who created it

    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:post_id])
    @comment = Comment.new(params.require(:comment).permit(:body))
    @comment.post = @post
    @comment.user = current_user


    if @comment.save
      flash[:notice] = "Comment created"
      redirect_to [@topic, @post]
    else
      flash[:error] = "Woopsie Daisy. Something went wrong."
      redirect_to [@topic, @post]
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def show
    @post = Post.find(params[:id])
    @topic = Topic.find(params[:topic_id])
    @comments = @post.comments
    authorize @post
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @post = Post.new
    authorize @post
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @post = Post.new(post_params)
    @post.user = current_user
    @post.topic = @topic
    authorize @post
    if @post.save
      flash[:notice] = "Post was saved."
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was an error saving the post. Please resubmit."
      render :new
    end
  end

  def edit
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    authorize @post
  end

  def update
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    authorize @post
    if @post.update_attributes(post_params)
      flash[:notice] = "Post was updated."
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :edit
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(params.require(:question).permit(:title, :body, :resolved))
    if @question.save
      flash[:notice] = "Question saved."
      redirect_to @question
    else
      flash[:error] = "There was an error saving the question. Please resubmit."
      render :new
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    if @question.update_attributes(params.require(:question).permit(:title, :body, :resolved))
      flash[:notice] = "Question was updated."
      redirect_to @question
    else
      flash[:error] = "There was an error saving the question. Please try again."
      render :edit
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.paginate(page: params[:page])
    authorize @topics
  end

  def new
    @topic = Topic.new
    authorize @topic
  end

  def show
    @topic = Topic.find(params[:id])
    @posts = @topic.posts.paginate(page: params[:page], per_page: 100)
    authorize @topic
  end

  def edit
    @topic = Topic.find(params[:id])
    authorize @topic
  end

  def create
    @topic = Topic.new(topic_params)
    authorize @topic
    if @topic.save
      flash[:notice] = "Topic created"
      redirect_to @topic
    else
      flash[:error] = "Woopsie Daisy. Something went wrong."
      render :new
    end
  end

  def update
    @topic = Topic.find(params[:id])
    authorize @topic
    if @topic.update_attributes(topic_params)
      flash[:notice] = "Success!"
      redirect_to @topic
    else
      flash[:error] = "Something went awry. Give it another go!"
      render :edit
    end
  end

  private

  def topic_params
    params.require(:topic).permit(:name, :description, :public)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def update
    if current_user.update_attributes(user_params)
      flash[:notice] = "User information updated"
      redirect_to edit_user_registration_path
    else
      flash[:error] = "Invalid user information"
      redirect_to edit_user_registration_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :avatar)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    #binding.pry
  end

  def about
  end

  def contact
  end

end

app/helpers/advertisements_helper.rb
module AdvertisementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def form_group_tag(errors, &block)
    if errors.any?
      content_tag :div, capture(&block), class: 'form-group has-error'
    else
      content_tag :div, capture(&block), class: 'form-group'
    end
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/advertisements/index.html.erb
<<h1>Advertisements</h1>
<% @advertisements.each do |ad| %>
  <div class='media'>
    <div class='media-body'>
      <h4 class='media-heading'>
        <%= link_to ad.title, ad %>
      </h4>
    </div>
  </div>
<% end %>

app/views/advertisements/show.html.erb
<h1><%= @advertisement.title %></h1>
<p><%= @advertisement.copy %></p>
<p><%= @advertisement.price %></p>

app/views/comments/_comment.html.erb
<% comments.each do |comment| %>
 <p><%= comment.body %></p>
<% end %>

app/views/comments/_form.html.erb
<%= form_for [topic, post, post.comments.new] do |f| %>
  <h4>Comments</h4>
  <p>Add a comment</p>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_field :body, class: 'form-control', placedholder: "Enter comment" %>
  </div>
  <div class="form-group">
    <%= f.submit "Create Comment", class: "btn btn-success" %>
  </div>
<% end %>

app/views/posts/_form.html.erb
<%= form_for [topic, post] do |f| %>
  <% if post.errors.any? %>
    <div class="alert alert-danger">
      <h4>There are <%= pluralize(post.errors.count, "error") %>.</h4>
      <ul>
        <% post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_group_tag(post.errors[:title]) do %>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
  <% end %>
  <%= form_group_tag(post.errors[:body]) do %>
    <%= f.label :body %>
    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
  <% end %>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image %>
    <%= f.hidden_field :image_cache %>
  </div>

  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for posts</p>
    <ul>
      <li>Make sure it rhymes.</li>
      <li>Don't use the letter "A".</li>
      <li>The incessant use of hashtags will get you banned.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= render partial: 'form', locals: { topic: @topic, post: @post } %>
  </div>
</div>

app/views/posts/index.html.erb
<h1>All Posts</h1>

<% if policy(Post.new).create? %>
  <%= link_to "New Post", new_post_path, class: "btn btn-success" %>
<% end %>
<% @posts && @posts.each do |post| %>
  <div class='media'>
    <div class='media-body'>
      <h4 class='media-heading'>
        <%= link_to post.title, post %>
      </h4>
      <small>
        submitted <%= time_ago_in_words(post.created_at) %> ago by <%= post.user.name %><br>
        <%= post.comments.count %> Comments
      </small>
    </div>
  </div>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for posts</p>
    <ul>
      <li>Make sure it rhymes.</li>
      <li>Don't use the letter "A".</li>
      <li>The incessant use of hashtags will get you banned.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= render partial: 'form', locals: { topic: @topic, post: @post} %>

  </div>
</div>

app/views/posts/show.html.erb
<h1><%= markdown_to_html @post.title %></h1>

<div class="row">
  <div class="col-md-8">
    <small>
      <%= image_tag(@post.user.avatar.tiny.url) if @post.user.avatar? %>
      submitted <%= time_ago_in_words(@post.created_at) %> ago by
      <%= @post.user.name %>
    </small>
    <p><%= markdown_to_html @post.body %></p>
    <%= render template: "comments/_form", locals: {topic: @topic, post: @post} %>
    <%= render template: "comments/_comment", locals: {comments: @post
      .comments} %>
  </div>
  <div class="col-md-4">
    <% if policy(@post).edit? %>
      <%= link_to "Edit", edit_topic_post_path(@topic, @post), class: "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/questions/edit.html.erb
<h1>Edit Question</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for questions:</p>
    <ul>
      <li>Clearly state your question.</li>
      <li>Include relevant examples, where possible.</li>
      <li>Keep questions succinct.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @question do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control", placeholder: "Enter question" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: "form-control", placeholder: "Enter response" %>
      </div>
      <div class="form-group">
        <%= f.label :resolved %>
        <%= f.check_box :resolved %>
      </div>
      <div class="form-group">
        <%= f.submit "Save", class: "btn btn-success" %>
      </div>
    <% end %>
  </div>
</div>

app/views/questions/index.html.erb
<h1>All Questions</h1>
<% @questions.each do |question| %>
  <div class='media'>
    <div class='media-body'>
      <h4 class='media-heading'>
        <%= link_to question.title, question %>
      </h4>
    </div>
  </div>
<% end %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for questions:</p>
    <ul>
      <li>Clearly state your question.</li>
      <li>Include relevant examples, where possible.</li>
      <li>Keep questions succinct.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @question do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control", placeholder: "Enter your question" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: "form-control", placeholder: "Enter response." %>
      </div>
      <div class="form-group">
        <%= f.submit "Save", class: "btn btn-success" %>
      </div>
    <% end %>
  </div>
</div>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>
<%= link_to "Edit", edit_question_path(@question), class: "btn btn-success" %>
<p><%= @question.body %></p>

app/views/topics/_form.html.erb
<%= form_for topic do |f| %>
  <% if topic.errors.any? %>
    <div class="alert alert-danger">
      <h4>There are <%= pluralize(topic.errors.count, "error") %>.</h4>
      <ul>
        <% topic.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_group_tag(topic.errors[:name]) do %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: "Enter a topic" %>
  <% end %>
  <%= form_group_tag(topic.errors[:description]) do %>
    <%= f.label :description %>
    <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter a summary for the topic" %>
  <% end %>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Edit Topic</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for topics:</p>
    <ul>
      <li>Make sure the topic is appropriate.</li>
      <li>Be concise</li>
      <li>Form complete thoughts</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= render partial: 'form', locals: { topic: @topic} %>
  </div>
</div>

app/views/topics/index.html.erb
<h1>Topics</h1>

<div class="row">
  <div class="col-md-8">
    <% @topics.each do |topic| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to topic.name, topic %>
          </h4>
          <small>
            <%= topic.description %>
          </small>
        </div>
      </div>
    <% end %>
    <%= will_paginate @topics, renderer: BootstrapPagination::Rails %>
  </div>
  <div class="col-md-4">
    <% if policy(Topic.new).create? %>
      <%= link_to "New Topic", new_topic_path, class: "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for topics:</p>
    <ul>
      <li>Make sure the topic is appropriate.</li>
      <li>Be concise</li>
      <li>Form complete thoughts</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= render partial: 'form', locals: { topic: @topic } %>
  </div>
</div>

app/views/topics/show.html.erb
<h1><%= @topic.name %></h1>

<% if policy(@topic).update? %>
  <%= link_to "Edit Topic", edit_topic_path, class: "btn btn-success" %>
<% end %>

<div class="row">
  <div class="col-md-8">
    <p class="lead"><%= @topic.description %></p>
    <% @posts.each do |post| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to (markdown_to_html post.title), [@topic, post] %>
          </h4>
          <small>
            <%= image_tag(post.user.avatar.tiny.url) if post.user.avatar? %>
            submitted <%= time_ago_in_words(post.created_at) %> ago by
            <%= post.user.name %><br>
            <%= post.comments.count %> Comments
          </small>
        </div>
      </div>
    <% end %>
    <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
  </div>
  <div class="col-md-4">
    <% if policy(Post.new).create? %>
      <%= link_to "New Post", new_topic_post_path(@topic), class: "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/welcome/about.html.erb
<h1>About Bloccit</h1>
<p>Created by: Me</p>
<%= link_to "Let's link up!", "https://www.linkedin.com/in/leoswalters", class: "btn btn-default btn-primary" %>

app/views/welcome/contact.html.erb
<h1>Welcome#contact</h1>
<p>Find me in app/views/welcome/contact.html.erb</p>

app/views/welcome/index.html.erb
<br>
<div class="jumbotron">
  <h1>Bloccit</h1>
  <p>Bloccit is a resource for sharing links with your friends!</p>
  <p>
    <%= link_to "Sign In", new_user_session_path, class: "btn btn-primary" %>
    <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary" %> today!
  </p>
</div>
<div class="row">
  <div class="col-md-4">
    <h2>Find important information</h2>
    <p>Find information and answers to some of the most sought after questions currently on the internet.</p>
  </div>
  <div class="col-md-4">
    <h2>Further enhance your skills</h2>
    <p>Bloccit offers many posts to further develop your skills.</p>
  </div>
  <div class="col-md-4">
    <h2>Share your knowledge</h2>
    <p>You're awesome. You should share all of that awesomeness with others in a post.</p>
  </div>
</div>